version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_mb-invoice-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - invoice_network

  backend:
    build: ./backend
    container_name: invoice_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: invoice_backend.settings

    ports:
      - "6200:8000" # External 6700 -> Internal Django port 8000
    volumes:
      - ./backend:/app
      - media_data:/app/media
    depends_on:
      - mysql
    networks:
      - invoice_network

  frontend:
    build: ./frontend
    container_name: invoice_frontend
    restart: always
    ports:
      - "6201:80" # External 6701 -> Internal Nginx serving frontend
    networks:
      - invoice_network
    depends_on:
      - backend # Optional, if frontend waits for backend during SSR/API calls

networks:
  invoice_network:
    driver: bridge

volumes:
  mysql_data:
  media_data:
