version: "3.9"

services:
  backend:
    build: ./backend
    container_name: invoice_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: shared-mysql
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: invoice_backend.settings

    ports:
      - "6200:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/media
    networks:
      - shared-db-network

  frontend:
    build: ./frontend
    container_name: invoice_frontend
    restart: always
    ports:
      - "6201:80"
    networks:
      - shared-db-network
    depends_on:
      - backend

networks:
  shared-db-network:
    external: true

volumes:
  media_data:
