# Generated by Django 5.1.7 on 2025-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=500)),
                ('branch_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('phone_code', models.CharField(default='+91', max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField()),
                ('series_prefix', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('last_invoice_number', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
