# Generated by Django 5.1.7 on 2025-04-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
