# Generated by Django 5.1.7 on 2025-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_gst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="gst",
            field=models.CharField(default=0.0, max_length=15),
        ),
        migrations.AlterField(
            model_name="client",
            name="vat",
            field=models.CharField(default=0.0, max_length=15),
        ),
    ]
