# Generated by Django 5.1.7 on 2025-04-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_client_gst_alter_client_vat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="gst",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="vat",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
