# Generated by Django 5.1.7 on 2025-04-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tax_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
