# Generated by Django 5.2 on 2025-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('tax_type', models.CharField(choices=[('gst', 'GST'), ('vat', 'VAT'), ('nil', 'Nil')], max_length=3)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('vat', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField()),
                ('invoice_series', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
