# Generated by Django 5.2 on 2025-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_code',
            field=models.CharField(default='+91', max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
