# Generated by Django 5.2 on 2026-01-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_phone_code_client_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice_series',
            field=models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_code',
            field=models.CharField(blank=True, default='+91', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('gst', 'GST'), ('vat', 'VAT'), ('nil', 'Nil')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
