# Generated by Django 5.2 on 2026-01-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_address_alter_client_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pincode',
        ),
    ]
