# Generated by Django 5.2 on 2026-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
