# Generated by Django 5.2 on 2025-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
