# Generated by Django 5.2 on 2025-09-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipping',
        ),
    ]
