# Generated by Django 5.2 on 2026-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
