# Generated by Django 5.2 on 2026-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_logo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='financial_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
